#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NuGetSearch.Android.Resource", IsApplication=true)]

namespace NuGetSearch.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NuGetSearch.Common.Android.Resource.String.library_name = global::NuGetSearch.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int packageDefaultIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int packageDefaultIconSmall = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int authors = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int authorsCaption = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int dependencies = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int dependenciesCaption = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int dependencyTitle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int dependencyVersionRange = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int description = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int detailLayout = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int headerLayout = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int icon = 2131165187;
			
			// aapt resource value: 0x7f070027
			public const int includePrereleaseMenu = 2131165223;
			
			// aapt resource value: 0x7f07000c
			public const int license = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int licenseCaption = 2131165195;
			
			// aapt resource value: 0x7f070022
			public const int loading = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int newSearchMenu = 2131165219;
			
			// aapt resource value: 0x7f070015
			public const int noNetwork = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int prerelease = 2131165191;
			
			// aapt resource value: 0x7f070025
			public const int prereleaseMenuGroup = 2131165221;
			
			// aapt resource value: 0x7f070021
			public const int progress = 2131165217;
			
			// aapt resource value: 0x7f07000a
			public const int projectSite = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int projectSiteCaption = 2131165193;
			
			// aapt resource value: 0x7f070012
			public const int relativeLayout1 = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int releaseTypeMenu = 2131165220;
			
			// aapt resource value: 0x7f070014
			public const int searchButton = 2131165204;
			
			// aapt resource value: 0x7f07001e
			public const int searchResultCount = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int searchResultLayout = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int searchResults = 2131165215;
			
			// aapt resource value: 0x7f070013
			public const int searchTerm = 2131165203;
			
			// aapt resource value: 0x7f07002c
			public const int sortByDateAddedMenu = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int sortByMenuGroup = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int sortByParentMenu = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int sortByPopularityMenu = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int sortByTitleMenu = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int stableOnlyMenu = 2131165222;
			
			// aapt resource value: 0x7f070016
			public const int statsLayout = 2131165206;
			
			// aapt resource value: 0x7f070020
			public const int text = 2131165216;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int totalPackageDownloads = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int totalPackageDownloadsCaption = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int totalPackages = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int totalPackagesCaption = 2131165212;
			
			// aapt resource value: 0x7f070017
			public const int uniquePackages = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int uniquePackagesCaption = 2131165208;
			
			// aapt resource value: 0x7f070005
			public const int version = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int versionHistory = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DependencyItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PackageDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Search = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SearchResultItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SearchResultLoadingItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int PackageDetailMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int SearchMenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040021
			public const int authors = 2130968609;
			
			// aapt resource value: 0x7f040018
			public const int dependencies = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int downloads = 2130968604;
			
			// aapt resource value: 0x7f04000a
			public const int exclude_prerelease_menu = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int include_prerelease = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int include_prerelease_menu = 2130968585;
			
			// aapt resource value: 0x7f04001d
			public const int last_updated = 2130968605;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int license = 2130968599;
			
			// aapt resource value: 0x7f04000d
			public const int new_search = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int new_search_menu = 2130968584;
			
			// aapt resource value: 0x7f04001f
			public const int no_network = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int no_network_title = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int ok = 2130968608;
			
			// aapt resource value: 0x7f040015
			public const int prerelease = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int project_site = 2130968598;
			
			// aapt resource value: 0x7f04000e
			public const int release_type = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int result_count_1 = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int result_count_format = 2130968587;
			
			// aapt resource value: 0x7f04001a
			public const int search_result_count_1 = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int search_result_count_format = 2130968601;
			
			// aapt resource value: 0x7f040011
			public const int sort_by = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int sort_by_date_added = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int sort_by_popularity = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int sort_by_title = 2130968595;
			
			// aapt resource value: 0x7f04000f
			public const int stable_only = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int total_package_downloads = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int total_packages = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int unique_packages = 2130968578;
			
			// aapt resource value: 0x7f04001b
			public const int version_history = 2130968603;
			
			// aapt resource value: 0x7f040006
			public const int wait_loading = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int wait_loading_more = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int wait_searching = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
